#!/bin/bash
set -e;

# Various overrides to make script run locally on OSX and without dokku
script_path=`dirname $0`
export DOKKU_ROOT=`pwd`
export LC_CTYPE=C
export LC_ALL=C
dokku () {
    $script_path/commands $@
}

chown () {
    # do nothing
    :
}

# Check if name is specified
if [[ $1 == db:* ]]; then
    if [[ -z $2 ]]; then
        echo "You must specify an app name"
        exit 1
    else
        APP="$2"
        # Check if app exists with the same name
        if [[ -d "$DOKKU_ROOT/$APP" ]]; then
            APP_EXISTS=true
        else
            APP_EXISTS=false
        fi
    fi
fi

# Create .db directory if does not exist
if [[ ! -d $DOKKU_ROOT/.db ]]; then
    mkdir -p $DOKKU_ROOT/.db
    chown -R dokku: $DOKKU_ROOT/.db
fi

case "$1" in

  db:create)
    DB_IMAGE=persistentdb/$APP
    # Check if DB container is installed
    IMAGE=$(docker images | grep "neam/persistentdb " |  awk '{print $3}')
    if [[ -z $IMAGE ]]; then
        echo "db image not found... Did you run '../docker-persistent-db/install' ?"
        exit 1
    fi
    # Check if an existing DB volume exists
    if [[ -f "$DOKKU_ROOT/.db/volume_$APP" ]]; then
        VOLUME="`cat $DOKKU_ROOT/.db/volume_$APP`:/opt/mysql"
        echo
        echo "-----> Reusing persistentdb/$APP database"
    else
        VOLUME="/opt/mysql"
        # Generate a random password for DB user
        DB_PASSWORD=$(< /dev/urandom tr -dc A-Za-z0-9 | head -c 16)
        echo $DB_PASSWORD > "$DOKKU_ROOT/.db/pwd_$APP"
        chown dokku: "$DOKKU_ROOT/.db/pwd_$APP"
        chmod 700 "$DOKKU_ROOT/.db/pwd_$APP"
    fi
    # Stop existing container with the same persistent DB
    ID=$(docker ps | grep "$DB_IMAGE":latest |  awk '{print $1}')
    if [[ ! -z "$ID" ]]; then
        docker stop $ID > /dev/null
    fi
    # Fork DB image
    ID=$(docker run -d neam/persistentdb /bin/bash -c "exit 0")
    docker wait $ID > /dev/null
    IMAGE=$(docker commit $ID)
    docker tag -f $IMAGE $DB_IMAGE
    # Launch container
    ID=$(docker run -v $VOLUME -p 3306 -d $DB_IMAGE /usr/bin/start_db.sh $DB_PASSWORD)
    sleep 4
    # Store persistent volume
    if [[ ! -f "$DOKKU_ROOT/.db/volume_$APP" ]]; then
        VOLUME_PATH=$(docker inspect $ID | grep /var/lib/docker/vfs/dir/ | awk '{print $2}' | sed -e's/"//g')
        if [[ -z $VOLUME_PATH ]]; then
            # Search in old location (<1.6)
            VOLUME_PATH=$(docker inspect $ID | grep /var/lib/docker/volumes/ | awk '{print $2}' | sed -e's/"//g')
        fi
        if [[ -z $VOLUME_PATH ]]; then
            echo "Your docker version is too old or too new (recommended version of Docker is 1.7.1)"
            exit 1
        fi
        echo $VOLUME_PATH > "$DOKKU_ROOT/.db/volume_$APP"
    fi
    # Write port for further usage
    PORT=$(docker port $ID 3306 | sed 's/0.0.0.0://')
    echo $PORT > "$DOKKU_ROOT/.db/port_$APP"
    # Link to a potential existing app
    dokku db:link $APP $APP
    echo
    echo "-----> db container created: $DB_IMAGE"
    sleep 1
    dokku db:info $APP
    ;;

  db:delete)
    DB_IMAGE=persistentdb/$APP
    ID=$(docker ps -a | grep "$DB_IMAGE":latest |  awk '{print $1}')
    # Stop the container
    if [[ ! -z $ID ]]; then
        docker kill $ID > /dev/null
        sleep 1
        docker rm $ID > /dev/null
        sleep 1
    fi
    # Remove image
    IMAGE=$(docker images | grep "$DB_IMAGE " |  awk '{print $1}')
    if [[ ! -z $IMAGE ]]; then
        docker rmi $IMAGE > /dev/null
    fi
    # Remove container port storage
    if [[ -f "$DOKKU_ROOT/.db/port_$APP" ]]; then
        rm -f "$DOKKU_ROOT/.db/port_$APP"
    fi
    # Remove container root password
    if [[ -f "$DOKKU_ROOT/.db/pwd_$APP" ]]; then
        rm -f "$DOKKU_ROOT/.db/pwd_$APP"
    fi
    # Remove persistent volume
    if [[ -f "$DOKKU_ROOT/.db/volume_$APP" ]]; then
        sleep 4
        rm -rf "$(cat $DOKKU_ROOT/.db/volume_$APP)"
        rm -f "$DOKKU_ROOT/.db/volume_$APP"
    fi
    echo
    echo "-----> db container deleted: $DB_IMAGE"
    ;;

  db:info)
    DB_IMAGE=persistentdb/$APP
    if [[ ! -f "$DOKKU_ROOT/.db/pwd_$APP" ]]; then
        echo "Unknown (or too old) db container"
        exit 1
    fi
    echo
    echo "       Host: 172.17.42.1"
    echo "       Port: $(cat "$DOKKU_ROOT/.db/port_$APP")"
    echo "       User: 'root'"
    echo "       Password: '$(cat "$DOKKU_ROOT/.db/pwd_$APP")'"
    echo "       Database: 'db'"
    echo
    ;;

  db:link)
    if $APP_EXISTS; then
        # Check argument
        if [[ -z $3 ]]; then
            echo "Linking db to $APP"
            DB_IMAGE="persistentdb/$APP"
            DB_PASSWORD=$(cat "$DOKKU_ROOT/.db/pwd_$APP")
            PORT=$(cat "$DOKKU_ROOT/.db/port_$APP")
            # Link database using dokku command
            dokku config:set $APP "DATABASE_URL=mysql2://root:$DB_PASSWORD@172.17.42.1:$PORT/db"
            #All DB-variables as ENV
            dokku config:set $APP "DB_HOST=172.17.42.1" "DB_PASS=$DB_PASSWORD" "DB_NAME=db" "DB_PORT=$PORT" "DB_USER=root"
            exit 1
        fi
        DB_IMAGE="persistentdb/$3"
        if [[ ! -f "$DOKKU_ROOT/.db/pwd_$3" ]]; then
            echo "Database is not initialized correctly"
            exit 1
        fi
        DB_PASSWORD=$(cat "$DOKKU_ROOT/.db/pwd_$3")
        PORT=$(cat "$DOKKU_ROOT/.db/port_$3")
        # Link database using dokku command
        dokku config:set $APP "DATABASE_URL=mysql2://root:$DB_PASSWORD@172.17.42.1:$PORT/db"
        #All DB-variables as ENV
        dokku config:set $APP "DB_HOST=172.17.42.1" "DB_PASSWORD=$DB_PASSWORD" "DB_NAME=db" "DB_PORT=$PORT" "DB_USER=root"
        
        echo
        echo "-----> $APP linked to $DB_IMAGE database"
    fi
    ;;

  db:console)
    if $APP_EXISTS; then
        # Check argument
        if [[ -z $2 ]]; then
            echo "You must specify a database name"
            exit 1
        fi
        DB_IMAGE="persistentdb/$2"
        if [[ ! -f "$DOKKU_ROOT/.db/pwd_$2" ]]; then
            echo "Database is not initialized correctly"
            exit 1
        fi
        DB_PASSWORD=$(cat "$DOKKU_ROOT/.db/pwd_$2")
        PORT=$(cat "$DOKKU_ROOT/.db/port_$2")
        # Open database using mysql-client
        mysql --host=172.17.42.1 --user=root --port="$PORT" --password="$DB_PASSWORD" db
    fi
    ;;

  db:dump)
    if $APP_EXISTS; then
        # Check argument
        if [[ -z $2 ]]; then
            echo "You must specify a database name"
            exit 1
        fi
        DB_IMAGE="persistentdb/$2"
        if [[ ! -f "$DOKKU_ROOT/.db/pwd_$2" ]]; then
            echo "Database is not initialized correctly"
            exit 1
        fi
        DB_PASSWORD=$(cat "$DOKKU_ROOT/.db/pwd_$2")
        PORT=$(cat "$DOKKU_ROOT/.db/port_$2")
        # Check if user gave a filename
        if [[ -z $3 ]]; then
            echo "Dumping to $2-dump$(date +%s).sql"
            mysqldump --host=172.17.42.1 --user=root --port="$PORT" --password="$DB_PASSWORD" db > "$2-dump$(date +%s).sql"
            exit 1
        fi
        mysqldump --host=172.17.42.1 --user=root --port="$PORT" --password="$DB_PASSWORD" db > $3
    fi
    ;;

  db:logs)
    DB_IMAGE=persistentdb/$APP
    ID=$(docker ps -a | grep "$DB_IMAGE" |  awk '{print $1}')
    docker logs $ID | tail -n 100
    ;;

  help)
    cat && cat<<EOF
    db:create <app>      Create a db container
    db:delete <app>      Delete specified db container
    db:info <app>        Display database informations
    db:link <app> <db>   Link an app to a db database
    db:console <app>     Open mysql-console to db container
    db:dump <app> <file> Dump default db database into file
    db:logs <app>        Display last logs from db container
EOF
    ;;

esac
